# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-TieRegistry
version:      0.25
version_from: TieRegistry.pm
installdirs:  site
requires:
    Carp:                          0
    Tie::Hash:                     0
    Win32API::Registry:            0.24

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
